In [1]:
import sklearn
import matplotlib.pyplot as plt
import pandas as pd
from sklearn.datasets import load_boston
from pandas_profiling import ProfileReport
from sklearn.datasets import load_boston
from sklearn.linear_model import LinearRegression
from sklearn.linear_model import LassoCV , Lasso ,Ridge , RidgeCV , ElasticNet ,ElasticNetCV
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split 
import seaborn as sns
import numpy as np
from sklearn.ensemble import RandomForestRegressor
from xgboost import XGBRegressor
import pickle

In [2]:
boston = load_boston()

In [3]:
df = pd.DataFrame(boston.data , columns=boston.feature_names)

In [4]:
df['price'] = boston.target

In [5]:
df.head()


CRIM    ZN  INDUS  CHAS    NOX     RM   AGE     DIS  RAD    TAX  \
0  0.00632  18.0   2.31   0.0  0.538  6.575  65.2  4.0900  1.0  296.0   
1  0.02731   0.0   7.07   0.0  0.469  6.421  78.9  4.9671  2.0  242.0   
2  0.02729   0.0   7.07   0.0  0.469  7.185  61.1  4.9671  2.0  242.0   
3  0.03237   0.0   2.18   0.0  0.458  6.998  45.8  6.0622  3.0  222.0   
4  0.06905   0.0   2.18   0.0  0.458  7.147  54.2  6.0622  3.0  222.0   

   PTRATIO       B  LSTAT  price  
0     15.3  396.90   4.98   24.0  
1     17.8  396.90   9.14   21.6  
2     17.8  392.83   4.03   34.7  
3     18.7  394.63   2.94   33.4  
4     18.7  396.90   5.33   36.2

Lets check the dataset have any missing or na values. What are the relations between feature.etc
with pandas profiling

In [6]:
a = ProfileReport(df)
a.to_widgets()

Summarize dataset:   0%|          | 0/27 [00:00<?, ?it/s]

Generate report structure:   0%|          | 0/1 [00:00<?, ?it/s]

Render widgets:   0%|          | 0/1 [00:00<?, ?it/s]

 creating a linear regression model

In [8]:
LR = LinearRegression()

In [9]:
y = df['price']
x= df.drop(columns=['price' ])

In [10]:
LR.fit(x,y)

LinearRegression()

In [11]:
LR.score(x,y)

0.7406426641094095

calculating r^2

In [12]:
def adjr2(r):
    le = r.score(x,y)
    adjr = 1 - ((1-le)*(506-1))/(506-13-1)
    return(adjr)
adjr2(LR)

0.733789726372463

In [ ]:
LR.intercept_

In [146]:
LR.coef_

array([-1.08011358e-01,  4.64204584e-02,  2.05586264e-02,  2.68673382e+00,
       -1.77666112e+01,  3.80986521e+00,  6.92224640e-04, -1.47556685e+00,
        3.06049479e-01, -1.23345939e-02, -9.52747232e-01,  9.31168327e-03,
       -5.24758378e-01])

In [153]:
LR.score(x,y)

0.739605684665497

In [14]:
x_train , x_test,y_train,y_test=train_test_split(x,y , test_size= 0.10 , random_state=100)

In [155]:
LR.fit(x_train,y_train)

LinearRegression()

In [156]:
LR.score(x_test,y_test)

0.8360934882713211

The accuracy of the data has been increased after splitting it.

In [157]:
LR.predict([[0.02731,0.0,7.07,0.0,0.469,6.421,78.9,4.9671,2.0,242.0,17.8,396.90,9.14]])

array([25.10459827])

Lets build a lasso model

In [158]:
lassocv = LassoCV(alphas= None , cv = 50,max_iter= 1000,normalize= True)
lassocv.fit(x_train,y_train)

LassoCV(cv=50, normalize=True)

In [159]:
lassocv.alpha_

0.0010519546472777023

In [160]:
lsm = Lasso(alpha=lassocv.alpha_)
lsm.fit(x_train,y_train)


Lasso(alpha=0.0010519546472777023)

In [161]:
lsm.score(x_test,y_test)

0.8358957129548839

In [162]:
lsm.predict([[0.02731,0.0,7.07,0.0,0.469,6.421,78.9,4.9671,2.0,242.0,17.8,396.90,9.14]])

array([25.09566583])

building Ridge model

In [163]:
Rd = RidgeCV(cv = 10,normalize= True)
Rd.fit(x_train,y_train)

RidgeCV(alphas=array([ 0.1,  1. , 10. ]), cv=10, normalize=True)

In [164]:
Rd.alpha_

0.1

In [165]:
ridge  = Ridge(alpha= Rd.alpha_)

In [166]:
ridge.fit(x_train,y_train)

Ridge(alpha=0.1)

In [167]:
ridge.score(x_test,y_test)

0.8357025640218911

In [168]:
ridge.predict([[0.02731,0.0,7.07,0.0,0.469,6.421,78.9,4.9671,2.0,242.0,17.8,396.90,9.14]])

array([25.0679438])

Building XGB model

In [169]:
xb = XGBRegressor()

In [170]:
xb.fit(x_train,y_train)

XGBRegressor(base_score=0.5, booster='gbtree', colsample_bylevel=1,
             colsample_bynode=1, colsample_bytree=1, gamma=0, gpu_id=-1,
             importance_type='gain', interaction_constraints='',
             learning_rate=0.300000012, max_delta_step=0, max_depth=6,
             min_child_weight=1, missing=nan, monotone_constraints='()',
             n_estimators=100, n_jobs=12, num_parallel_tree=1, random_state=0,
             reg_alpha=0, reg_lambda=1, scale_pos_weight=1, subsample=1,
             tree_method='exact', validate_parameters=1, verbosity=None)

In [171]:
xb.score(x_test,y_test)

0.8095806094512317

Building randomforest model

In [15]:
rd = RandomForestRegressor()
rd.fit(x_train,y_train)

RandomForestRegressor()

In [16]:
rd.score(x_test,y_test)

0.8350514985167617

In [17]:
rd.predict([[0.02731,0.0,7.07,0.0,0.469,6.421,78.9,4.9671,2.0,242.0,17.8,396.90,9.14]])

array([21.72])

random forest has the best prediction till now


Lets create a elastic regressor model


In [175]:
elastic = ElasticNetCV(alphas= None , cv = 10)
elastic.fit(x_train,y_train)

ElasticNetCV(cv=10)

In [176]:
elastic.alpha_

1.4333273140925005

In [177]:
elastic.l1_ratio_

0.5

In [178]:
elsaticlr = ElasticNet(alpha= elastic.alpha_ ,l1_ratio= elastic.l1_ratio_)

In [179]:
elsaticlr.fit(x_train,y_train)

ElasticNet(alpha=1.4333273140925005)

In [180]:
elsaticlr.score(x_test,y_test)

0.6734685741379984

In [184]:
elsaticlr.predict([[0.02731,0.0,7.07,0.0,0.469,6.421,78.9,4.9671,2.0,242.0,17.8,396.90,9.14]])

array([25.89186487])

dumping the random forest model using pickle

In [189]:
pickle.dump(rd,open('admi_pred_mo_rd.pickle' , 'wb'))

In [18]:
ls

 Volume in drive C is OS_Install
 Volume Serial Number is E88F-2898

 Directory of C:\Users\rohan

23-09-2021  01:08    <DIR>          .
23-09-2021  01:08    <DIR>          ..
25-08-2021  11:03    <DIR>          .anaconda
21-09-2021  18:34    <DIR>          .conda
25-08-2021  11:01                25 .condarc
25-08-2021  11:01    <DIR>          .continuum
02-09-2021  23:47    <DIR>          .cufflinks
23-09-2021  00:51                60 .gitconfig
21-09-2021  22:05    <DIR>          .ipynb_checkpoints
28-08-2021  09:04    <DIR>          .ipython
21-09-2021  22:07    <DIR>          .jupyter
30-08-2021  14:47    <DIR>          .matplotlib
23-09-2021  00:55               204 _netrc
24-08-2021  20:00    <DIR>          3D Objects
21-09-2021  22:58               646 admi_pred_mo.pickle
21-09-2021  23:04         3,512,009 admi_pred_mo_rd.pickle
28-08-2021  09:56           581,076 All types Of Feature Transformation.ipynb
20-09-2021  20:28            95,047 boston.ipynb
24-08-2021  20:00    <DI